languageCode = "en-us"
title = "Snoom Security"
baseurl = "/"
theme = "basics"
PygmentsCodeFences = true
pygmentsStyle = ["solarized-dark"]

[params]
	author = "Snoom"
	github = "thesnoom"
	description = "Security and all that malarkey..."
	authorlocation = "Hmm."
