languageCode = "en-us"
title = "Snoom Security"
baseurl = "/"
theme = "basics"

[params]
	author = "Snoom"
	github = "thesnoom"
	description = "Security and all that malarkey..."
	authorlocation = "Hmm."
